name: number_trivia
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  realm: ^1.0.3
  flutter_modular: ^5.0.3
  equatable: ^2.0.5
  http: ^0.13.5
  dartz: ^0.10.1
  data_connection_checker_nulls: ^0.0.2
  modal_progress_hud_nsn: ^0.4.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true